### ISSUE TITLE
Launching on mac: don't assume it's always an .app bundle

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#2131]
For example, Deceiver has this lil' manifest:

```toml
[[actions]]
name = "play"
path = "LASERCRABS.app/Contents/MacOS/lasercrabs-launcher"
scope = "profile:me"
```

And then we have this lovely error:

```
Could not get executable path for app bundle (/Users/rccmac1/Library/Application Support/itch/apps/deceiver/LASERCRABS.app/Contents/MacOS/lasercrabs-launcher)
```

...because, of course, it's not a bundle.

So smaug's `app` and `sandboxexec` runners need to be non-app-aware.

In fact, it should first:

  * Resolve the executable to its bundle, if it's in a bundle
  * If it's not in a bundle, do the right thing
    * for example, not use `open -W` for the `app` runner
    * and not make a shim bundle for the `sandboxexec` runner, because we don't Resources/Info.plist to symlink.

I really wish I had a physical mac right now.
